"""Create Podium

Revision ID: da39d786abfe
Revises: 0e2ed395df39
Create Date: 2023-12-07 09:01:06.765051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da39d786abfe'
down_revision: Union[str, None] = '0e2ed395df39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('podium',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.Column('first_place_id', sa.Integer(), nullable=True),
    sa.Column('second_place_id', sa.Integer(), nullable=True),
    sa.Column('third_place_id', sa.Integer(), nullable=True),
    sa.Column('fourth_place_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['first_place_id'], ['competitors.id'], ),
    sa.ForeignKeyConstraint(['fourth_place_id'], ['competitors.id'], ),
    sa.ForeignKeyConstraint(['second_place_id'], ['competitors.id'], ),
    sa.ForeignKeyConstraint(['third_place_id'], ['competitors.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('podium')
    # ### end Alembic commands ###
