"""Adding txt

Revision ID: e2bf33329b46
Revises: 134c8adb8494
Create Date: 2023-12-07 08:22:15.721672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2bf33329b46'
down_revision: Union[str, None] = '134c8adb8494'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('txt', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'txt')
    # ### end Alembic commands ###
